import Foundation

/// Defines strict text correction rules applied right before streaming insertion or clipboard write,
/// mitigating common LLM dictation/translation formatting issues (similar to openless's
/// `apply_correction_rules`).
public enum TextCorrectionRules {
    
    /// Applies all correction rules to the given text.
    public static func apply(to text: String) -> String {
        var corrected = text
        
        // Rule 1: Add space between Chinese characters and English letters/numbers.
        // openless: fixes '测试A' -> '测试 A'
        corrected = applyRegex(
            pattern: "([\\p{Script=Han}])([A-Za-z0-9])",
            replacement: "$1 $2",
            to: corrected
        )
        corrected = applyRegex(
            pattern: "([A-Za-z0-9])([\\p{Script=Han}])",
            replacement: "$1 $2",
            to: corrected
        )
        
        // Rule 2: Deduplicate repetitive Chinese punctuation generated by aggressive streaming ASR/LLMs.
        corrected = applyRegex(
            pattern: "([。，！？；：])\\1+",
            replacement: "$1",
            to: corrected
        )
        
        return corrected
    }
    
    private static func applyRegex(pattern: String, replacement: String, to text: String) -> String {
        do {
            let regex = try NSRegularExpression(pattern: pattern, options: [])
            return regex.stringByReplacingMatches(
                in: text,
                options: [],
                range: NSRange(text.startIndex..., in: text),
                withTemplate: replacement
            )
        } catch {
            return text
        }
    }
}
