import Foundation

// MARK: - Narrow candidate card
//
// A runnable legal skill action. Built per-skill by `LegalCaptureCoordinator.candidateCard`
// for the 划词菜单 direct run, then executed via the privacy-gated path. Generated by the
// router + registry — rules-first, no model wait (spec §6 / §7).

/// What clicking a candidate does.
public enum LegalCandidateAction: Codable, Sendable {
    case executeSkill(skillId: String)
    case askUserToSelectScene
    case openSettings
}

public struct LegalCandidateCard: Codable, Sendable, Identifiable {
    public let id: String
    public let skillId: String
    public let title: String
    public let subtitle: String
    public let scene: LegalScene
    public let stage: LegalStage
    public let confidence: Double
    public let badges: [String]                  // 如 "诉讼" / "待核" / "本地优先"
    public let requiredInputs: [LegalSkillInputField]
    public let preview: String?
    public let action: LegalCandidateAction

    public init(
        id: String,
        skillId: String,
        title: String,
        subtitle: String = "",
        scene: LegalScene,
        stage: LegalStage,
        confidence: Double,
        badges: [String] = [],
        requiredInputs: [LegalSkillInputField] = [],
        preview: String? = nil,
        action: LegalCandidateAction
    ) {
        self.id = id
        self.skillId = skillId
        self.title = title
        self.subtitle = subtitle
        self.scene = scene
        self.stage = stage
        self.confidence = confidence
        self.badges = badges
        self.requiredInputs = requiredInputs
        self.preview = preview
        self.action = action
    }

    /// A copy with one more badge (236: mark imported skills 第三方·未审). No-op if present.
    public func addingBadge(_ badge: String) -> LegalCandidateCard {
        guard !badges.contains(badge) else { return self }
        return LegalCandidateCard(
            id: id, skillId: skillId, title: title, subtitle: subtitle,
            scene: scene, stage: stage, confidence: confidence,
            badges: badges + [badge], requiredInputs: requiredInputs,
            preview: preview, action: action)
    }
}
